<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ef19696a-319b-4e24-b33a-17f8d0a4e6a2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Layout\logoBillTrick.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Layout\logoBillTrick.png">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.10.0" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.10.0" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="7.1.2" />
    <PackageReference Include="Radzen.Blazor" Version="3.20.11" />
    <PackageReference Include="Refit" Version="8.0.0" />
    <PackageReference Include="Refit.HttpClientFactory" Version="8.0.0" />
    <PackageReference Include="rix0rrr.BeaconLib" Version="1.0.2" />
	<PackageReference Include="Syncfusion.Blazor" Version="32.1.23" />
	<PackageReference Include="Syncfusion.Blazor.Themes" Version="32.1.23" />
	<PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
	<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\Admin\History\" />
    <Folder Include="Pages\Users\" />
    <Folder Include="wwwroot\js\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\assetlen.Shared.Models\assetlen.Shared.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Pages\Admin\Settings\ReceiptDesigner\ReceiptPrinterSelect.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Pages\BillingModule\Payments\ChequeDetails.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Pages\Components\SearchListMini.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Pages\OrdersModule\ChangeSaleStatus.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="wwwroot\welcomeimage.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>